version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/lottery
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
