version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/lottery

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after_install_prod.sh
      timeout: 500
      runas: ubuntu
