name: Deploy to AWS EC2 via CodeDeploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Set to your AWS region

      - name: Trigger AWS CodeBuild
        run: |
          aws codebuild start-build --project-name Live_Carpgear --region eu-west-2

      - name: Upload Artifact to S3
        run: |
          aws s3 cp artifacts/deploy.zip s3://livecarpgeardeployments/deployments/latest.zip --region eu-west-2

      - name: Deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name Live_Carpgear \
            --deployment-group-name Live_Carpgear \
            --s3-location bucket=livecarpgeardeployments,key=deployments/latest.zip,bundleType=zip \
            --region eu-west-2

